apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal-crud-deployment
spec:
  selector:
    matchLabels:
      app: job-portal-crud-mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: job-portal-crud-mysql
    spec:
      containers:
        - name: job-portal-crud-kube
          image: fevly/job-portal-crud-kube:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql

            - name: DB_NAME
              value: jobsearchportal

            - name: DB_USERNAME
              value: root

            - name: DB_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: job-portal-crud-svc
spec:
  selector:
    app: job-portal-crud-mysql
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort